### ISSUE TITLE
Association is broken

### ISSUE THREAD

**Issue by jasonmcintosh** [USSBA/terraform-aws-waf-regional#3]
https://github.com/USSBA/terraform-aws-waf-regional/blob/master/waf.tf#L189

Depends upon a value of 1, where-as it's a boolean type.  Needs to be changed to 
```
  count        = var.enabled ? length(var.alb_arns) : 0
```

**Comment by jasonmcintosh** [comment]
Fixed by:
https://github.com/USSBA/terraform-aws-waf-regional/pull/4

**Comment by jsmigovsky** [comment]
@jasonmcintosh sorry for the long wait
your pull request has been merged and a version has been issued. v1.1.1
